### ISSUE TITLE
数据集地址下载不了

### ISSUE THREAD

**Issue by HonestyBrave** [HeinzJiao/PolyR-CNN#2]
博主你好，readme中：“The preprocessed CrowdAI dataset can be downloaded [here](https://github.com/HeinzJiao/PolyR-CNN?tab=readme-ov-file#) (Google Drive link to be provided).”  here下载地址好像链接的还是github地址，不是google网盘地址，下载不了。博主可否更新下？

**Comment by HeinzJiao** [comment]
你好，感谢你对我们工作的关注。目前，预处理后的CrowdAI数据集及模型的其他细节正在整理和上传过程中。如果你有紧急需求，建议你先下载CrowdAI数据集（[https://www.aicrowd.com/challenges/mapping-challenge#dataset](url)），并按照我们README中提供的预处理代码自行处理。感谢你的理解与支持。

**Comment by HonestyBrave** [comment]
好的，多谢啦！
